name: Monitor Cita Brasilia

on:
  schedule:
    - cron: "*/5 * * * *"   # 5 minutos (mude p/ */10 se quiser 10)
  workflow_dispatch:
    inputs:
      test_alert:
        description: "Enviar teste no Telegram (1 = sim)"
        required: false
        default: "0"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests
          playwright install --with-deps chromium

      - name: Run monitor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MONITOR_URL: ${{ secrets.MONITOR_URL }}
          TEST_ALERT: ${{ github.event.inputs.test_alert || secrets.TEST_ALERT || '0' }}
        run: python monitor.py
