name: Monitor Cita Brasilia

on:
  schedule:
    - cron: "*/10 * * * *"   # 5 minutos (troque para */3 ou */10 se quiser)
  workflow_dispatch:
    inputs:
      test_alert:
        description: "Enviar teste no Telegram (1 = sim)"
        required: false
        default: "0"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests
          playwright install --with-deps chromium

      - name: Run monitor
        env:
          MONITOR_URL: ${{ secrets.MONITOR_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TEST_ALERT: ${{ github.event.inputs.test_alert }}
        run: |
          python monitor.py
