name: Monitor Cita Brasilia

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
    inputs:
      test_alert:
        description: "Enviar alerta de teste no Telegram (1 = sim)"
        required: false
        default: "0"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Run monitor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FORCE_TEST_ALERT: ${{ github.event.inputs.test_alert }}
        run: |
          python monitor.py
